# Heavily referenced from github starter-workflows template:
# https://github.com/actions/starter-workflows/blob/61d42c9d0c8d4a398799a581eb6ce48ca742a2bc/ci/docker-publish.yml

name: Build container image
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-container-image:
    name: Build container image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Login to GHCR
        id: docker-login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        id: docker-setup
        uses: docker/setup-buildx-action@v3
      
      - name: Generate Docker Metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Build & Push docker image
        id: docker-build-push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }} # Don't push on pulls to avoid griefing.
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
