name: Build container image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-container-image:
    name: Build container image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build container image
        run: docker build . -t ghcr.io/0xba5e64/tailbb:${{ github.sha }}
      
      - name: Push container to GHCR
        run: docker push ghcr.io/0xba5e64/tailbb:${{ github.sha }}
